# Generated by Django 3.2 on 2021-05-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='counter_value',
            field=models.IntegerField(default=0),
        ),
    ]
